
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      
      - run: yarn install --skip-integrity-check

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests and lint
      - run: yarn lint
      # - run: yarn test

workflows:
  version: 2
  test:
    jobs:
      - test